#!/usr/bin/env bash
# desktop.sh - helpers for the stagos-desktop modules (sourced, not executed).
# Every helper is idempotent and honours DRY_RUN=1 (via run() from common.sh).
# shellcheck disable=SC2034  # DM_CHANGED is read by the entry script

DM_CHANGED=0     # files (re)written this run; a second run should leave this at 0
DM_NOTES=()      # things a container cannot check; printed at the end

dm_note() { DM_NOTES+=("$*"); }
dm_dry() { [[ "${DRY_RUN:-0}" == "1" ]]; }
dm_have_systemd() { [[ -d /run/systemd/system ]]; }
dm_cfg() { echo "${XDG_CONFIG_HOME:-$HOME/.config}"; }

# dm_pkgs pkg...: official repo packages
dm_pkgs() { run sudo pacman -S --needed --noconfirm "$@"; }

# dm_aur pkg...: AUR packages via paru (built from source by provision/10-aur.sh if missing)
dm_aur() {
  if ! have paru; then
    # shellcheck source=provision/10-aur.sh
    source "$HERE/provision/10-aur.sh"
    stagos_10_aur || { warn "paru unavailable, skipping AUR: $*"; return 0; }
  fi
  run paru -S --needed --noconfirm "$@" || warn "AUR install failed: $*"
}

# dm_flatpak id...: Flathub apps (system-wide remote, idempotent)
dm_flatpak() {
  dm_pkgs flatpak
  run sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  local id
  for id in "$@"; do
    if ! dm_dry && flatpak info "$id" >/dev/null 2>&1; then continue; fi
    run sudo flatpak install -y --noninteractive flathub "$id" || warn "flatpak install failed: $id"
  done
}

# dm_install SRC DST [MODE] [sudo]: copy only when content differs
dm_install() {
  local src="$1" dst="$2" mode="${3:-644}" as="${4:-}"
  if dm_dry; then run ${as:+sudo} install -Dm"$mode" "$src" "$dst"; return 0; fi
  if [[ -f "$dst" ]] && cmp -s "$src" "$dst" && [[ "$(stat -c %a "$dst")" == "$mode" ]]; then return 0; fi
  ${as:+sudo} install -Dm"$mode" "$src" "$dst"
  DM_CHANGED=$((DM_CHANGED + 1))
  log "wrote $dst"
}

# dm_write DST [MODE] [sudo]: like dm_install, content from stdin
dm_write() {
  local dst="$1" mode="${2:-644}" as="${3:-}" tmp
  tmp="$(mktemp)"
  cat > "$tmp"
  if dm_dry; then log "[dry] would write $dst"; rm -f "$tmp"; return 0; fi
  dm_install "$tmp" "$dst" "$mode" "$as"
  rm -f "$tmp"
}

# dm_sync_dir SRCDIR DSTDIR: copy every file (keeps exec bit), never deletes
dm_sync_dir() {
  local src="$1" dst="$2" f rel mode
  while IFS= read -r -d '' f; do
    rel="${f#"$src"/}"
    mode=644; [[ -x "$f" ]] && mode=755
    dm_install "$f" "$dst/$rel" "$mode"
  done < <(find "$src" -type f -print0 | sort -z)
}

# dm_config NAME...: sync desktop/NAME into ~/.config/NAME
dm_config() {
  local n
  for n in "$@"; do dm_sync_dir "$HERE/desktop/$n" "$(dm_cfg)/$n"; done
}

# dm_bins NAME...: install desktop/bin/NAME.sh as /usr/local/bin/NAME
dm_bins() {
  local n
  for n in "$@"; do dm_install "$HERE/desktop/bin/$n.sh" "/usr/local/bin/$n" 755 sudo; done
}

# dm_env_write: (re)write ~/.config/stagos/desktop.env, the public runtime tunables (stag-plasma-apply --session)
dm_env_write() {
  dm_write "$(dm_cfg)/stagos/desktop.env" 644 <<ENVEOF
# generated by stagos-desktop from config/stagos.conf; edit there, then rerun \`stagos-desktop hidpi\`
STAGOS_OUTPUT_SCALE=${STAGOS_OUTPUT_SCALE:-1.5}
ENVEOF
}

# dm_enable_system UNIT...: enable at boot (and start) a system unit; skipped without a running systemd
dm_enable_system() {
  if ! dm_have_systemd && ! dm_dry; then dm_note "enable system unit(s): $*"; return 0; fi
  run sudo systemctl enable --now "$@" || warn "could not enable: $*"
}

# dm_enable_user UNIT...: same for the user manager
dm_enable_user() {
  if ! dm_have_systemd && ! dm_dry; then dm_note "enable user unit(s): $*"; return 0; fi
  run systemctl --user enable "$@" || warn "could not enable (user): $*"
}

# dm_root_fstype: filesystem of / (override with STAGOS_ROOT_FSTYPE for tests)
dm_root_fstype() {
  if [[ -n "${STAGOS_ROOT_FSTYPE:-}" ]]; then echo "$STAGOS_ROOT_FSTYPE"; else findmnt -no FSTYPE / 2>/dev/null || echo unknown; fi
}

# dm_line_in_file FILE LINE: append LINE if not present (creates FILE)
dm_line_in_file() {
  if dm_dry; then log "[dry] ensure line in $1: $2"; return 0; fi
  mkdir -p "$(dirname "$1")"; touch "$1"
  grep -qxF -- "$2" "$1" || { printf '%s\n' "$2" >> "$1"; DM_CHANGED=$((DM_CHANGED + 1)); }
}

# dm_add_group GROUP: add the desktop user to a group if it isn't in it
dm_add_group() {
  if dm_dry; then run sudo usermod -aG "$1" "$USER"; return 0; fi
  id -nG "$USER" | tr ' ' '\n' | grep -qx "$1" && return 0
  sudo usermod -aG "$1" "$USER" && DM_CHANGED=$((DM_CHANGED + 1)) && dm_note "group $1 added: log out and in again"
}
