#!/usr/bin/env bash
# Link: StagOS <-> StagSystem on the desktop.
#  - ntfy: stag-ntfy topics (STAGOS_NTFY_TOPICS, default stag-alerts,stag-agents) as Plasma notifications,
#    stagos-ntfy.service (systemd --user, with Plasma). Host/port/user from config/local.conf; the password
#    or token goes in ~/.config/stagos/ntfy.credentials (600, created empty once, Jack fills it).
#    Off switch: [link] ntfy=false in ~/.config/stagos/desktop.conf.
#  - KRunner: the StagOS D-Bus runner (t <task>, ask <question>, stag <app>), per user, started on demand.
#  - KDE Connect: kdeconnect, plus the firewall drop-in /etc/nftables.d/kdeconnect.nft (TCP/UDP 1714-1764).
#    STAGOS_LINK_KDECONNECT=0 skips it.
stagos_dm_link() {
  dm_pkgs python python-dbus python-gobject libnotify xdg-utils curl
  local lib="$HOME/.local/lib/stagos" data="${XDG_DATA_HOME:-$HOME/.local/share}" src="$HERE/desktop/link"
  dm_install "$src/stag-ntfy-notify.py" "$lib/stag-ntfy-notify" 755
  dm_install "$src/stag-krunner.py" "$lib/stag-krunner" 755
  dm_install "$src/stag-ntfy.svg" "$data/icons/hicolor/scalable/apps/stag-ntfy.svg" 644
  dm_install "$src/stag-ntfy.desktop" "$data/applications/stag-ntfy.desktop" 644
  stagos_link_ntfy
  stagos_link_krunner
  stagos_link_kdeconnect
}

# stagos_link_user_unit UNIT BEFORE: enable UNIT (wanted by plasma-workspace.target) and, inside a running
# Plasma, restart it when files changed since DM_CHANGED was BEFORE (start it when it is down).
stagos_link_user_unit() {
  local unit="$1" before="$2"
  if dm_dry; then dm_note "link: systemctl --user enable $unit (dry run)"; return 0; fi
  if ! systemctl --user show-environment >/dev/null 2>&1; then
    dm_note "link: no systemd user manager running; after login run: systemctl --user enable --now $unit"
    return 0
  fi
  [[ "$DM_CHANGED" != "$before" ]] && systemctl --user daemon-reload
  if ! systemctl --user is-enabled --quiet "$unit" 2>/dev/null; then
    if systemctl --user enable "$unit" >/dev/null 2>&1; then
      DM_CHANGED=$((DM_CHANGED + 1)); log "enabled $unit"
    else
      warn "could not enable $unit"
    fi
  fi
  systemctl --user is-active --quiet plasma-workspace.target 2>/dev/null || return 0
  if [[ "$DM_CHANGED" != "$before" ]]; then
    systemctl --user restart "$unit" || warn "could not start $unit"
  elif ! systemctl --user is-active --quiet "$unit" 2>/dev/null; then
    systemctl --user start "$unit" || warn "could not start $unit"
  fi
}

stagos_link_ntfy() {
  local before="$DM_CHANGED" cfg; cfg="$(dm_cfg)/stagos"
  local host="${STAGOS_NTFY_HOST:-${STAGOS_STAG_HOST:-}}" port="${STAGOS_NTFY_PORT:-8443}"
  local user="${STAGOS_NTFY_USER:-}" topics="${STAGOS_NTFY_TOPICS:-stag-alerts,stag-agents}" creds="$cfg/ntfy.credentials"
  if [[ -z "$host" || "$host" == CHANGEME* ]]; then
    warn "link: no ntfy host (STAGOS_NTFY_HOST or STAGOS_STAG_HOST in config/local.conf): notifications stay off"
  elif ! [[ "$port" =~ ^[0-9]{1,5}$ && "$host" =~ ^[A-Za-z0-9.-]+$ ]]; then
    warn "link: STAGOS_NTFY_HOST/STAGOS_NTFY_PORT look wrong ($host:$port): notifications stay off"
  else
    # not secret, but the host is private: 600 like stag-services
    dm_write "$cfg/link.env" 600 <<ENVEOF
# generated by stagos-desktop link from config/local.conf (STAGOS_NTFY_*); edit there, then rerun \`stagos-desktop link\`
NTFY_URL=https://$host:$port
NTFY_USER=$user
NTFY_TOPICS=$topics
ENVEOF
  fi
  # the credentials file: created empty once, never overwritten, never read or printed here
  if dm_dry; then
    log "[dry] would create $creds (600) if missing"
  elif [[ -L "$creds" ]]; then
    warn "link: $creds is a symlink; stag-ntfy-notify refuses it, replace it with a plain file (mode 600)"
  elif [[ ! -e "$creds" ]]; then
    dm_install "$HERE/desktop/link/ntfy.credentials.example" "$creds" 600
    dm_note "link: fill in $creds (NTFY_PASSWORD for ntfy user '${user:-?}', or NTFY_TOKEN), then: systemctl --user restart stagos-ntfy"
  elif [[ "$(stat -c %a "$creds")" != 600 ]]; then
    chmod 600 "$creds"; DM_CHANGED=$((DM_CHANGED + 1)); log "chmod 600 $creds"
  fi
  [[ -n "$user" ]] || dm_note "link: STAGOS_NTFY_USER is empty: set it in config/local.conf, or put NTFY_TOKEN in $creds"
  dm_install "$HERE/desktop/link/stagos-ntfy.service" "$(dm_cfg)/systemd/user/stagos-ntfy.service" 644
  stagos_link_user_unit stagos-ntfy.service "$before"
}

stagos_link_krunner() {
  local before="$DM_CHANGED" data="${XDG_DATA_HOME:-$HOME/.local/share}" src="$HERE/desktop/link"
  dm_install "$src/stagos-krunner.desktop" "$data/krunner/dbusplugins/stagos-krunner.desktop" 644
  sed "s|@HOME@|$HOME|" "$src/org.stagos.krunner.service.in" | dm_write "$data/dbus-1/services/org.stagos.krunner.service" 644
  dm_install "$src/stagos-krunner.service" "$(dm_cfg)/systemd/user/stagos-krunner.service" 644
  # D-Bus activated, nothing to enable; a changed runner must not keep running the old code
  if [[ "$DM_CHANGED" != "$before" ]] && ! dm_dry && systemctl --user show-environment >/dev/null 2>&1; then
    systemctl --user daemon-reload
    systemctl --user try-restart stagos-krunner.service 2>/dev/null || true
  fi
}

stagos_link_kdeconnect() {
  if [[ "${STAGOS_LINK_KDECONNECT:-1}" != 1 ]]; then
    dm_note "link: STAGOS_LINK_KDECONNECT=0, KDE Connect skipped"
    return 0
  fi
  dm_pkgs kdeconnect sshfs
  # inert until the firewall module's /etc/nftables.conf includes /etc/nftables.d/*.nft
  dm_install "$HERE/desktop/link/kdeconnect.nft" /etc/nftables.d/kdeconnect.nft 644 sudo
  local rs
  if ! dm_dry && have nft && rs="$(sudo nft list ruleset 2>/dev/null)" && [[ -n "$rs" && "$rs" != *1714-1764* ]]; then
    # the StagOS firewall (module firewall) is loaded without the drop-in: reload just its table
    if [[ "$rs" == *"table inet stagos"* ]] && sudo nft -c -f /etc/nftables.conf 2>/dev/null; then
      run sudo nft -f /etc/nftables.conf || dm_note "link: could not reload the firewall; run: stag-fw on"
    else
      dm_note "link: a firewall is active without the KDE Connect ports; reload it (StagOS firewall: stag-fw on)"
    fi
  fi
}
